import type { SnapshotDiff } from '../scan/history.js';
import { computeHealthScore, type HealthScore } from '../scan/health-score.js';
import type { ProjectSnapshot } from '../scan/snapshot.js';

export function renderMarkdownReport(
  snapshot: ProjectSnapshot,
  health: HealthScore,
  diff?: SnapshotDiff | null,
  dashboardUrl?: string,
): string {
  const lines: string[] = [];
  const s = snapshot.summary;

  lines.push(`# Sublyzer Snapshot — ${snapshot.projectName}`);
  lines.push('');
  lines.push(`**Generated:** ${snapshot.scannedAt}  `);
  lines.push(`**Stack:** ${snapshot.stack.label}  `);
  lines.push(`**Health:** ${health.score}/100 (grade ${health.grade})  `);
  if (dashboardUrl) lines.push(`**Dashboard:** ${dashboardUrl}  `);
  lines.push('');

  lines.push('## Summary');
  lines.push('');
  lines.push('| Metric | Value |');
  lines.push('|--------|-------|');
  lines.push(`| Routes | ${s.routeCount} |`);
  lines.push(`| Dependencies | ${s.productionDeps} prod / ${s.devDeps} dev |`);
  lines.push(`| Vulnerabilities | ${s.vulnerablePackages} (C:${s.criticalVulns} H:${s.highVulns}) |`);
  if (snapshot.outdated?.ran) {
    lines.push(`| Outdated packages | ${snapshot.outdated.total} (${snapshot.outdated.majorCount} major) |`);
  }
  if (snapshot.git.available) {
    lines.push(`| Git | \`${snapshot.git.branch}@${snapshot.git.commit}\`${snapshot.git.dirty ? ' *(dirty)*' : ''} |`);
  }
  lines.push('');

  if (health.factors.length) {
    lines.push('## Health factors');
    lines.push('');
    for (const f of health.factors) {
      const sign = f.impact >= 0 ? '+' : '';
      lines.push(`- ${f.label} (${sign}${f.impact})`);
    }
    lines.push('');
  }

  if (diff && diff.previousAt) {
    lines.push('## Changes since last scan');
    lines.push('');
    lines.push(`Previous scan: ${diff.previousAt}`);
    lines.push('');
    if (diff.healthDelta != null) {
      const arrow = diff.healthDelta >= 0 ? '↑' : '↓';
      lines.push(`- Health score: ${arrow} ${Math.abs(diff.healthDelta)} points`);
    }
    if (diff.vulnDelta.total !== 0) {
      lines.push(`- Vulnerabilities: ${diff.vulnDelta.total >= 0 ? '+' : ''}${diff.vulnDelta.total}`);
    }
    if (diff.routesAdded.length) {
      lines.push(`- Routes added (${diff.routesAdded.length}): ${diff.routesAdded.slice(0, 10).join(', ')}`);
    }
    if (diff.routesRemoved.length) {
      lines.push(`- Routes removed (${diff.routesRemoved.length}): ${diff.routesRemoved.slice(0, 10).join(', ')}`);
    }
    lines.push('');
  }

  if (snapshot.audit.advisories.length) {
    lines.push('## Top vulnerabilities');
    lines.push('');
    lines.push('| Severity | Package | Title |');
    lines.push('|----------|---------|-------|');
    for (const a of snapshot.audit.advisories.slice(0, 10)) {
      lines.push(`| ${a.severity} | ${a.name} | ${a.title.replace(/\|/g, '/')} |`);
    }
    lines.push('');
  }

  if (snapshot.routes.length) {
    lines.push('## Routes');
    lines.push('');
    for (const r of snapshot.routes.slice(0, 50)) {
      lines.push(`- \`${r}\``);
    }
    if (snapshot.routes.length > 50) {
      lines.push(`- … +${snapshot.routes.length - 50} more`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('*Generated by [sublyzer-snapshot](https://github.com/sublyzer-one/sublyzer-snapshot)*');
  lines.push('');

  return lines.join('\n');
}
