import * as fs from 'node:fs';
import * as path from 'node:path';
import { ok, title, info } from '../utils/log.js';

const WORKFLOW = `# Generated by sublyzer-snapshot ci — commit or customize as needed
name: Sublyzer Snapshot

on:
  push:
    branches: [main, master]
  pull_request:
  schedule:
    - cron: '0 9 * * 1'  # Weekly Monday 09:00 UTC

jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm

      - name: Install Sublyzer Snapshot
        run: npm install -g sublyzer-snapshot@latest

      - name: Link integration
        env:
          SUBLYZER_INTEGRATION_CODE: \${{ secrets.SUBLYZER_INTEGRATION_CODE }}
        run: sublyzer-snapshot init --code "$SUBLYZER_INTEGRATION_CODE" -y

      - name: Scan and push
        run: sublyzer-snapshot run --fail-on high --json > snapshot-result.json

      - name: Upload report
        run: sublyzer-snapshot report --out sublyzer-report.md

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: sublyzer-snapshot
          path: |
            snapshot-result.json
            sublyzer-report.md
`;

export type CiOptions = {
  out?: string;
  print?: boolean;
};

export async function runCi(opts: CiOptions = {}): Promise<{ path: string; content: string }> {
  const outPath = path.resolve(process.cwd(), opts.out || '.github/workflows/sublyzer-snapshot.yml');
  const content = WORKFLOW;

  if (opts.print !== false && !opts.out) {
    title('Sublyzer Snapshot — CI template');
    console.log(content);
    info('Save to .github/workflows/sublyzer-snapshot.yml and add secret SUBLYZER_INTEGRATION_CODE');
    return { path: outPath, content };
  }

  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  if (fs.existsSync(outPath)) {
    throw new Error(`File already exists: ${outPath} (use --out to pick another path)`);
  }
  fs.writeFileSync(outPath, content, 'utf8');
  ok(`Wrote ${outPath}`);
  info('Add GitHub secret: SUBLYZER_INTEGRATION_CODE');
  return { path: outPath, content };
}
